CREATE TABLE `company_settings` (
	`id` text PRIMARY KEY DEFAULT 'default' NOT NULL,
	`company_name` text NOT NULL,
	`postal_code` text,
	`address` text NOT NULL,
	`building` text,
	`registration_number` text NOT NULL,
	`bank_name` text NOT NULL,
	`bank_branch` text NOT NULL,
	`bank_branch_code` text,
	`bank_account_type` text DEFAULT '普通預金',
	`bank_account_name` text NOT NULL,
	`bank_account_number` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `engineers` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`name_kana` text,
	`age` integer,
	`gender` text,
	`nearest_station` text,
	`experience_years` integer,
	`skills` text DEFAULT '[]' NOT NULL,
	`skill_summary` text,
	`desired_unit_price` integer,
	`min_unit_price` integer,
	`status` text DEFAULT '待機中' NOT NULL,
	`availability_date` text,
	`project_id` text,
	`contract_end_date` text,
	`engineer_type` text DEFAULT '自社' NOT NULL,
	`affiliation_company` text,
	`parent_company` text,
	`billing_unit_price` integer,
	`standard_hours_min` integer,
	`standard_hours_max` integer,
	`cost_unit_price` integer,
	`remarks` text,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` text PRIMARY KEY NOT NULL,
	`invoice_number` text,
	`issue_date` text NOT NULL,
	`due_date` text,
	`client_name` text NOT NULL,
	`engineer_id` text,
	`project_id` text,
	`billing_month` text NOT NULL,
	`unit_price` integer NOT NULL,
	`actual_hours` integer,
	`standard_hours_min` integer DEFAULT 140,
	`standard_hours_max` integer DEFAULT 180,
	`deduction_rate` integer,
	`overtime_rate` integer,
	`travel_expenses` integer DEFAULT 0,
	`tax_rate` integer DEFAULT 10,
	`status` text DEFAULT '下書き',
	`notes` text,
	`created_at` text NOT NULL,
	`updated_at` text,
	`sent_at` text,
	`paid_at` text,
	FOREIGN KEY (`engineer_id`) REFERENCES `engineers`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `orders` (
	`id` text PRIMARY KEY NOT NULL,
	`order_number` text,
	`issue_date` text NOT NULL,
	`order_type` text DEFAULT '注文書',
	`project_id` text,
	`project_name` text NOT NULL,
	`engineer_id` text,
	`engineer_name` text,
	`client_company` text NOT NULL,
	`sender_company` text,
	`sender_registration_number` text,
	`sender_address` text,
	`sender_signature` text,
	`order_amount` integer,
	`amount_subtotal` integer,
	`tax_amount` integer,
	`unit_price` integer,
	`cost_unit_price` integer,
	`engineer_affiliation_company` text,
	`cost_deduction_rate` integer,
	`cost_overtime_rate` integer,
	`engineer_parent_company` text,
	`months` integer,
	`period_start` text,
	`period_end` text,
	`standard_hours_min` integer,
	`standard_hours_max` integer,
	`overtime_rate` integer,
	`deduction_rate` integer,
	`contract_type` text,
	`settlement_unit` text,
	`transportation` text,
	`deliverable` text,
	`tax_rate` integer DEFAULT 10,
	`status` text DEFAULT '下書き',
	`notes` text,
	`created_at` text NOT NULL,
	`updated_at` text,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`engineer_id`) REFERENCES `engineers`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `projects` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`client_company` text,
	`client_address` text,
	`client_contact_name` text,
	`client_contact_email` text,
	`client_contact_tel` text,
	`agency_company` text,
	`agency_address` text,
	`agency_contact_name` text,
	`agency_contact_email` text,
	`status` text DEFAULT '商談中' NOT NULL,
	`start_date` text,
	`end_date` text,
	`work_location` text,
	`remarks` text
);
